spring:
  datasource:
    url: jdbc:mysql://localhost:3307/coding_db_schema
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: Projekt X
  jpa:
    show-sql: true
